version: '3.9'

services:
  nodejs-application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - app-network
    depends_on:
      - mongodatabase

  mongodatabase:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    networks:
      - app-network
    environment:
      - MONGO_INITDB_DATABASE=devsecops
  
networks:
  app-network:
    driver: bridge
